### PR TITLE
#12 introduce `FlowPanel`

### LINKED ISSUE #12: FlowPanel
Facilitate the creation of `JPanel` with `FlowLayout`.

### PR DESCRIPTION
**Pull request by Adeynack**
closes #12

### CODE REVIEW

**Comment by danpersa** [comment]
is anybody still using swing? I thought javafx is the "future"...

**Comment by danpersa** [comment]
👍

**Comment by Adeynack** [comment]
@danpersa : Yes: me ;) The [plugin for Moneydance](https://github.com/Adeynack/Mundane-Kotlin) I am working on is based on Swing. I could do it in JavaFX as well and integrate it in Swing, but it complicates things when it comes to the tread pool management. Also, the _Moneydance_ software provides some specialised Swing components so it's better just to leverage it.

**Comment by Adeynack** [comment]
@danpersa : Also, this project is not using Zappr. You need to go to "Files Changed" and "Approve" your review.

**Review by danpersa — APPROVED** [review]

**Pull request merged**
